### ISSUE TITLE
Can you please change the minimum android platform to 5.0.0

### ISSUE THREAD

**Issue by alexhisen** [Steffaan/cordova-plugin-local-notifications#10]
i.e. in plugin.xml instead of
engine name="cordova-android" version=">=6.0.0"
change to
engine name="cordova-android" version=">=5.0.0"
Although cordova-android older than 6.3 defaults to android-23, 24 or 25 and this plugin needs 26, it's possible to use older cordova-android platform (at least as old as 5.x) and manually specify which SDK level you want to compile against with target=android-26 in project.properties.
We've tested this plugin and it works just fine with cordova-android 5.2.2.

**Comment by Steffaan** [comment]
Adjusted the version and commited https://github.com/Steffaan/cordova-plugin-local-notifications/commit/6e65c949a5abe974afc9b48c80d6b08b192f85f9
