### ISSUE TITLE
Android API compatibility

### ISSUE THREAD

**Issue by tehmaestro** [Steffaan/cordova-plugin-local-notifications#11]
Hi. I was wondering if you fork is compatible with Android API level 19+ ? I tried 0.9.2-beta.3 from the main repository and it crashed on Android 4.4
By the way, awesome work creating this fork!

**Comment by Steffaan** [comment]
I don't have any Android 4.4 devices around at the moment. So please try it out and let me know how it goes.

**Comment by tehmaestro** [comment]
It did work on 4.4, I just thought you had exact specs.
This issue confuses me :) https://github.com/katzer/cordova-plugin-local-notifications/issues/1490

**Comment by Steffaan** [comment]
That's based on the beta version, master version supports 4.4 😄 

I'm closing this issue for now, let me know if there are any other issues.

**Comment by tehmaestro** [comment]
Cool. Thanks!
