### ISSUE TITLE
Question only.

### ISSUE THREAD

**Issue by CreativeArtDesign** [Steffaan/cordova-plugin-local-notifications#14]
Hi, I am new at this, this fork should work as it says, I only wonder how to install this fork in my ionic 4 project.

I hope there are somebody who can guide me to install this in some easy step for a beginner.

Best regards

Kamal

**Comment by Steffaan** [comment]
Delete the original plugin that's installed right now and add this fork with the following code:

`ionic cordova plugin add https://github.com/Steffaan/cordova-plugin-local-notifications.git`

Be sure to read the main page for instructions and provide channels to make the notifications work on Android 8+. Example of the code providing a channel:

```
cordova.plugins.notification.local.schedule({
    channel: 'myFirstChannel',
    title: 'My first channel',
    text: 'Thats pretty easy...'
});
```

**Comment by CreativeArtDesign** [comment]
The sound working fine with ogg and some of wav files but did not manage mp3 files. 
I am satisfied with ogg works fine for me.

**One more Question: When start a new blank app from scratch**
First i execute this line below that you send me in a new project
`ionic cordova plugin add https://github.com/Steffaan/cordova-plugin-local-notifications.git`

But it was not enough so i becuase i got an error that says notification does not exist.
So I  execute this this line to? Then i got no errors
`npm install @ionic-native/local-notifications`

Little confused at this. Why is there two lines that should executed?

In my new project do i need  native audio to get the notification to play or no need?

Thanks for your help.
