### ISSUE TITLE
cordova.plugins.notification.local.schedule works first time, crashes every other time

### ISSUE THREAD

**Issue by salem0426** [Steffaan/cordova-plugin-local-notifications#16]
**WARNING: IF YOU IGNORE THIS TEMPLATE, WE'LL IGNORE YOUR ISSUE. YOU MUST FILL THIS IN!**

First notification is successful. Every other notification crashes the app

## Your Environment

* Plugin version: cordova-plugin-local-notification 0.9.2
* Platform: iOS
* OS version: 12.0.1
* Device manufacturer / model: iPhone 7 (MNAJ2LL/A)
* Cordova version (```cordova -v```): 8.1.2 (cordova-lib@8.1.1)
* Cordova platform version (```cordova platform ls```): 
Installed platforms:
  ios 4.5.5
* Plugin config
cordova-plugin-aws-user-pool 1.1.0 "Aws UserPool sdk"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-ble-central 1.2.2 "BLE"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-dbcopy 2.1.2 "sqlDB"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-file 4.3.3 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googleplus 5.3.2 "Google SignIn"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-local-notification 0.9.2 "LocalNotification"
cordova-plugin-nativeaudio 3.0.9 "Cordova Native Audio"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.6.0 "Cordova sqlite storage plugin"
* Ionic Version (if using Ionic)

## Expected Behavior

Notification pop-ups work every time

## Actual Behavior

First notification is successful. Every other notification crashes the app in UNUserNotificationCenter(APPLocalNotification) getNotificationWithID Line 131

## Steps to Reproduce

Happens consistently

## Context

Code snippet:
cordova.plugins.notification.local.schedule({
title: 'PEARL Alert',
text:inText,
smallIcon: 'res://noti-logo.png',
icon: 'file://img/noti-logo.jpg',
vibrate:true,
lockscreen:true,
foreground: true,
actions: [
acts
function(data){
console.log("Notification callback: ",data);
}
]
});

## Debug logs

_Include iOS / Android logs_

  * ios XCode logs
2019-03-03 15:26:27.735880-0500 PEARL[2178:698268] 15:26:27:730 Scheduling notification is moving for item Aircraft
2019-03-03 15:26:27.753769-0500 PEARL[2178:698819] -[NSNull stringValue]: unrecognized selector sent to instance 0x23fc659a0
2019-03-03 15:41:49.352519-0500 PEARL[2178:698819] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull stringValue]: unrecognized selector sent to instance 0x23fc659a0'
*** First throw call stack:
(0x20f793ef8 0x20e961a40 0x20f6ab154 0x20f799810 0x20f79b4bc 0x1003b6904 0x1003abdd0 0x100bdb840 0x100bdcde4 0x100bdfcac 0x100bee1f8 0x100beebe4 0x20f3ae190 0x20f3b0d00)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by salem0426** [comment]
Additional information regarding Notifications working for the first time: Receives a one time only pop-up asking to allow Notifications for iOS Application
![image1-12](https://user-images.githubusercontent.com/48187496/53727765-00469c00-3e3f-11e9-8504-8c16f68576c3.jpeg)

**Comment by salem0426** [comment]
Neglected to indicate that this issue is with iOS devices only. Notifications for this App on Android phones works just fine.

**Comment by Steffaan** [comment]
The issue is in your code, debug your javascript and check if all your variables are set correct.  Especially this piece of code:
```
actions: [
acts
function(data){
console.log("Notification callback: ",data);
}
]
```

What is `acts` ?

**Comment by Steffaan** [comment]
You need to provide the actions like this:
```
actions: [
                    { id: 'firstAction', title: 'Your first action' },
                    { id: 'secondAction', title: 'Your second action' }
]
```

And catch them like this:
```
cordova.plugins.notification.local.on('firstAction', function (data, eopts) {
            // Your code
});

cordova.plugins.notification.local.on('secondAction', function (data, eopts) {
            // Your code
});
```

**Comment by salem0426** [comment]
Steffaan: Thank you for responding. I am looking to use cordova.plugins.notification.local.schedule to be called from my App with a message argument.

Every time the function is called, cordova.plugings.notification.local.schedule displays the message.

Currently, this only works for the initial call and not for any other calls.

Any suggestions on how to get this to work would be most appreciated!
Thanks,
salem0426
