### ISSUE TITLE
Terminating app due to uncaught exception - index 0 beyond bounds for empty array

### ISSUE THREAD

**Issue by vincentfierant** [Steffaan/cordova-plugin-local-notifications#19]
Copied from https://github.com/katzer/cordova-plugin-local-notifications/issues/1657, but since I use your fork, please could you look at this issue?

> All methods returns same error, iOS only:
> 2018-08-06 10:14:57.086475+0300 *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndexedSubscript:]: index 0 beyond bounds for empty array'
> 
> Ionic, iOS - android is fine!
> 
> * Plugin version: 0.9.0-beta.3
> * Platform: iOS
> * OS version: 11.4
> * Device manufacturer / model: Apple iPhone X
> * Cordova version (`cordova -v`): 8.0.0
> * Cordova platform version (`cordova platform ls`): android 7.0.0,  ios 4.5.4
> * Plugin config
> * Ionic Version (if using Ionic): 3.20.0
> 
> ## Expected Behavior
> The getAll & schedule methods should work :)

**Comment by Steffaan** [comment]
I have merged your pull request. Thanks!
