### ISSUE TITLE
Time in notification with progress bar get reseted after notification update

### ISSUE THREAD

**Issue by hordesalik** [Steffaan/cordova-plugin-local-notifications#2]
Android 8.1
Cordova 8.0.0
Cordova Android 7.1.0

When I'm creating notification with progressBar, there is a timer appears near the notification title. But when I'm updating progress bar value it get set to 00:00 and counter starts again. You can try next snippet:
```javascript
cordova.plugins.notification.local.schedule({
            id: 1,
            channel: 'progress',
            title: 'Downloading...',
            text: 'File name',
            sound: false,
            vibrate: false,
            foreground: false,
            progressBar: {value: 0},
        });

        for (var i = 1; i <= 10; i++) {
            (function (i) {
                setTimeout(function () {
                    cordova.plugins.notification.local.update({
                        id: 1,
                        progressBar: {value: i * 10},
                    })
                }, i * 3000);
            })(i);
        }
```

It was working properly before fix #1

**Comment by Steffaan** [comment]
Pass the property `channel` inside your update payload and it should work fine. Since the plugin now supports multiple channels, it's fallback is to use the default channel name if no channel name is given.

Let me know if it works.

**Comment by hordesalik** [comment]
Nope, it didn't help

**Comment by hordesalik** [comment]
Hi @Steffaan 
Any progress or info here?

**Comment by Steffaan** [comment]
Fixed in commit https://github.com/Steffaan/cordova-plugin-local-notifications/commit/27687fd5c87b89bb993912b7df7053b9c9ee2e63 and merged to master.
