### ISSUE TITLE
Update readme with installation instructions

### ISSUE THREAD

**Issue by Simpler1** [Steffaan/cordova-plugin-local-notifications#3]
Hi Steffaan,

Thanks for taking on this plugin.  

Can you update the readme with installation instructions?  Since your fork is not handled by npm, what are the manual steps to swap to this fork?

Also, the changelog is reporting 0.8.5 as the version.  I would be good to update to 0.9.1 for consistency.

Thanks again...

**Comment by Steffaan** [comment]
Updated the Changelog and Readme.

I also included a new section in the Readme which explains the new channels for Android.
