### ISSUE TITLE
Scheduled notifications not working on all phones

### ISSUE THREAD

**Issue by gotters** [Steffaan/cordova-plugin-local-notifications#4]
I am running ionic and using the 0.8 version of the plugin since the 0.9 is not compatible with ionic.
I am scheduling notifications to run daily and I have it working in some cases but in others - like my Nexus 5 running Android 8.1 I am having problems.

The scheduled notification runs perfectly the first time. 
If I do a json dump of all the notifications on my phone I can see all the pending scheduled notifications but they never seem to fire - only the first one fires.

I am just wondering if this is an issue thats been resolved in the newer version?
Also will your forked version become compatible with ionic native or any way to get it working with ionic native?

Thanks

**Comment by Steffaan** [comment]
Version 0.8 isn't compatible with Android 8+, that's one of the main reason this fork was created. Using this fork will fix your issues with Android 8 devices.

So to answer your first question, yes it has been resolved in this version.

To answer your second question, I'm not working with ionic native at the moment. I dont expect to do so anytime soon.

**Comment by Steffaan** [comment]
Closing this issue for now, since it's not an actual issue but a question (that has been answered just now).

**Comment by gotters** [comment]
Thanks for the info - appreciate it.
