### ISSUE TITLE
Different (and not desired) notification behavior

### ISSUE THREAD

**Issue by andersborgabiro** [Steffaan/cordova-plugin-local-notifications#5]
Notifications are sticky and full-length whatever options I set.

## Your Environment

* Plugin version: 979c65e
* Platform: Android
* OS version: 7
* Device manufacturer / model: Sony Xperia L1
* Cordova version (```cordova -v```): cli-8.0.0
* Cordova platform version (```cordova platform ls```): 7.0.0
* Plugin config: Installed via PhoneGap Build
* Ionic Version (if using Ionic)

## Expected Behavior

The katzer plugin shows one truncated line of text and the notification disappears on activation or Clear All. Doesn't matter what I set, the behavior is not the same with your plugin.

## Actual Behavior

Notifications are sticky and full-length whatever options I set.

## Steps to Reproduce

I set this:

        cordova.plugins.notification.local.schedule(
                {
                    channel: "Primary",
                    id: NOTIFICATIONID,
                    text: message,
                    badge: badge,
                    autoClear: true,
                    sticky: false,
                    ongoing: false // seemingly not used anymore
                }
        );

## Context

See above.

## Debug logs

I haven't seen any exceptions. Log can be added if needed.

**Comment by Steffaan** [comment]
There is no difference between the two, regarding to the notification settings / workflow. 

The whole notification code is unchanged, so I can't imagine the behaviour being different from the original plugin. 

Still, because this version supports multiple channels, perhaps you created the channel earlier (by providing a notification) and it's configuration is different from your other notifications?

Try uninstalling your app (this will clear all existing channels) and trigger the notification again after reinstalling. 

Don't just install a new version over the current one, you must uninstall your current app manually before installing again.

**Comment by andersborgabiro** [comment]
I uninstalled each time, but I noticed I've been using de.appplant.cordova.plugin.local-notification that works the way I need it to (non-sticky, one line). I'll see if cordova-plugin-local-notifications can be made to behave the same. Thanks.

**Comment by andersborgabiro** [comment]
The de.appplant.cordova.plugin.local-notification and cordova-plugin-local-notifications pages at NPM point to the same GitHub repository page, so that confused me. The released plugins behave differently though, and the prior the way I need.

In any case, I'll use your fork and try to set it to behave like the appplant plugin. The sticky behavior needs to go. I can cut the text string in my code if it can't be forced to be one line via the plugin.

**Comment by andersborgabiro** [comment]
This might be of interest (there was no exception for Android 8 of course).

Devices with problems
Google Pixel 2 (walleye) - Android 9

Exception
android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=-2 contentView=null vibrate=null sound=null defaults=0x0 flags=0x42 color=0x00000000 vis=PRIVATE)
