### ISSUE TITLE
Question on recent merge in katzer version

### ISSUE THREAD

**Issue by alexhisen** [Steffaan/cordova-plugin-local-notifications#9]
Is this recently merged fix - https://github.com/katzer/cordova-plugin-local-notifications/pull/1611 - relevant to this fork?

And do you plan to submit PR for the changes in your fork to katzer?

Thanks.

**Comment by Steffaan** [comment]
I will check out the merged changes and include them if necessary.

Katzer recently commented on the main repo, telling that he still maintains the plugin and will continue supporting it soon, so I'm going to check out how things are going in the near future and will submit a PR if he agrees with our changes.

**Comment by Steffaan** [comment]
All changes from master are included in the fork now (https://github.com/Steffaan/cordova-plugin-local-notifications/commit/6e65c949a5abe974afc9b48c80d6b08b192f85f9)
